### ISSUE TITLE
Publish pre-compiled version of shifty so library can be used by projects built with create-react-app

### ISSUE THREAD

**Issue by aholachek** [jeremyckahn/shifty#104]
Hi, thanks for this awesome library, I'm using it as a dependency in a [React animation library I recently worked on](https://github.com/aholachek/react-flip-toolkit). 

Because shifty is not currently compiled to ES5 in dist/ it throws an error when someone tries to compile it in certain webpack setups, e.g. those created with create-react-app. [Here's a description of the error.](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Would you be willing to publish a transpiled version? For now, I'm going to try just copying the relevant files into my library.

**Comment by aholachek** [comment]
wait, nevermind, I think this was due to the way I was importing only certain files from the src/ directory

**Comment by jeremyckahn** [comment]
😄

Thanks for taking the time to file this issue and dig into it further! react-flip-toolkit looks really cool, and I’m glad to see that Shifty is working well for you. Feel free to open another issue if see an opportunity for improvement to the library!
