### ISSUE TITLE
shifty doesn't work on external display with another macbook

### ISSUE THREAD

**Issue by wheam** [jeremyckahn/shifty#106]
I have a Acer PE270 display, when I use my macbook pro 2017 15', shifty works fine on the external display, when I use my macbook pro 2017 13',  shifty doesn't work, I dont know why

**Comment by jeremyckahn** [comment]
Hi @wheam, that’s really bizarre. It kind of sounds like a transient browser issue. Have you tried using a different browser, or perhaps restarting your current one?

Is it just a specific demo/example that doesn’t work?

**Comment by wheam** [comment]
shifty off with macbook pro 15' , internal display and external display are same
![img_2005](https://user-images.githubusercontent.com/2664774/49417717-e4891680-f7b9-11e8-9abb-4464bb624b31.jpg)

shifty on with macbook pro 15' , internal display and external display are same
![img_2010](https://user-images.githubusercontent.com/2664774/49417719-e521ad00-f7b9-11e8-9bec-861671425d74.jpg)

shifty on with macbook pro 13' , internal display and external display are not same
![img_2011](https://user-images.githubusercontent.com/2664774/49417720-e521ad00-f7b9-11e8-92ef-d2ef1a5261e7.jpg)

shifty off with macbook pro 13' , internal display and external display are same
![img_2006](https://user-images.githubusercontent.com/2664774/49417718-e4891680-f7b9-11e8-8bd9-e44bad36394e.jpg)

**Comment by wheam** [comment]
sorry, the pictures are broken. I mean shifty just works on internal display  but not external display when I use macbook pro 13'.

**Comment by jeremyckahn** [comment]
That’s truly bizarre. Please do post working images of what you are seeing, or at least share the URL(s) where the issue can be seen – it’s a little hard for me to start understanding what’s going on without at least one of those!

**Comment by jeremyckahn** [comment]
I believe you are posting to the wrong GitHub project. I think you want https://github.com/thompsonate/Shifty. 🙂

**Comment by wheam** [comment]
oh，no，sorry
