### ISSUE TITLE
Module exports not working correctly with default gatsby webpack config

### ISSUE THREAD

**Issue by andru** [jeremyckahn/shifty#112]
Using the default webpack config provided by [gatsby](https://github.com/gatsbyjs/gatsby), importing tween from shifty using the es6 import statement `import {tween} from 'shifty'` I'm running into the error `Object(...) is not a function` because `tween` is `undefined`.

If I import the default export from the  `shifty` module, I can access tween at `shifty.shifty.tween`:

```js
import shifty, {tween} from 'shifty';

tween(...);
// > error: Object(...) is not a function

typeof tween
// > undefined

shifty.shifty.tween(...);
// > all ok
```

just to clarify it's not the mixing of the main module export and a named module export: 

```js 
import {tween} from 'shifty';

typeof tween
// > undefined
```

Digging a little deeper, it looks like webpack isn't able to resolve any named exports - it can only resolve the default export, i.e. `import {tween} from 'shifty'` statement is can't actually find a `tween` export:

![image](https://user-images.githubusercontent.com/30393/54473346-857e6900-47ce-11e9-8731-4b8d9e660b51.png)

Looking at the webpack stats, I can see that it's resolving `shifty` to `dist/shifty.node.js`; I don't know exactly how that differs from the `dist/shifty.js`, or how webpack determines to resolve to one or the other, but I guess that's the root of the issue? 

Adding an `alias` to the webpack config to resolve `shifty` to `node_modules/shifty/src` or to `node_modules/shifty/dist/shifty.js` resolves the issue.

```js
      alias: {
        shifty: path.resolve(__dirname, 'node_modules/shifty/dist/shifty.js'),
      },
```

```js 
import {tween} from 'shifty';

typeof tween
// > function
```

Tested on `2.7.3` and `2.7.4-alpha.2`, with gatsby@2.1.35

I haven't run into this with any other libraries using the default gatsby webpack config, so I thought it would be more appropriate to raise this here rather than over at the gatsby repo.

**Comment by jeremyckahn** [comment]
Hi @andru, thanks for opening this issue, and for debugging it as much as you have! It's not immediately clear to me what's causing this, but it may be related to the [recent upgrade to Webpack 4](https://github.com/jeremyckahn/shifty/commit/84b030fe06f627ab3fa593eb06ae831e8d4416b4) and [subsequent change to generate separate browser and Node bundles](https://github.com/jeremyckahn/shifty/commit/547cfe85d969e14f2a900a73cb844757874a2b74). The second change was needed because Webpack 4 no longer generates bundles that work in both environments, and the only difference between `dist/shifty.js` and `dist/shifty.node.js` should be that the former references `window` and the latter references `global`. This is as best as I understand how to properly use Webpack 4, anyways — I would love to know if this could be improved!

> Looking at the webpack stats, I can see that it's resolving shifty to dist/shifty.node.js; I don't know exactly how that differs from the dist/shifty.js, or how webpack determines to resolve to one or the other, but I guess that's the root of the issue?

I would expect that Webpack uses the same file resolution logic as NPM. I used [this documentation as a basis](https://docs.npmjs.com/files/package.json#main) for separating the browser and non-browser bundles. I might have this wrong though and I think you might be onto something here.

It's a bit hard for me to deduce what's causing this without seeing the issue firsthand — are you able to provide steps for me to reproduce this?

**Comment by jeremyckahn** [comment]
FYI, I attempted to reproduce this locally from a fresh Gatsby site install (`npx gatsby new my-blazing-fast-site`). I made these changes:

```diff
diff --git a/package.json b/package.json
index eeed2e4..ff9d416 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,8 @@
     "prop-types": "^15.7.2",
     "react": "^16.8.4",
     "react-dom": "^16.8.4",
-    "react-helmet": "^5.2.0"
+    "react-helmet": "^5.2.0",
+    "shifty": "^2.7.4-alpha.2"
   },
   "devDependencies": {
     "prettier": "^1.16.4"
diff --git a/src/pages/index.js b/src/pages/index.js
index 2079a12..183f77c 100644
--- a/src/pages/index.js
+++ b/src/pages/index.js
@@ -5,6 +5,16 @@ import Layout from "../components/layout"
 import Image from "../components/image"
 import SEO from "../components/seo"
 
+import { tween } from "shifty"
+
+tween({
+  from: { x: 0 },
+  to: { x: 10 },
+  step: ({ x }) => {
+    console.log(x)
+  },
+})
+
 const IndexPage = () => (
   <Layout>
     <SEO title="Home" keywords={[`gatsby`, `application`, `react`]} />
```

The `tween` function loads and runs in my browser and everything appears to be working as expected. I have never used Gatsby before though, so perhaps this is not effectively reproducing the issue you're experiencing.

**Comment by andru** [comment]
Iiiiinteresting. I'm using a different the [gatsby-universal](https://github.com/fabe/gatsby-universal) starter template, which shows this issue fresh out of the box, but you're quite right that the issue doesn't exist with the [default starter template ](https://github.com/gatsbyjs/gatsby-starter-default). Thanks for taking the time to have a look at that, I should have thought to try it on the default starter template 🤦‍♂️

There must be some config or library in the universal template which is causing this, so I'll dig a bit deeper and get back to you as to whether this has any bearing on this library.

Thanks!

**Comment by andru** [comment]
Hunted the issue down to [directory-named-webpack-plugin](https://www.npmjs.com/package/directory-named-webpack-plugin), which resolves to filenames matching their parent directory. I'm not entirely clear why it's a problem for this library, since the relevant files in this repo are `dist/shifty.js` and `dist/shifty.node.js`, and yet more confusingly it seems to be preferring the latter, but....

Adding `exclude: /node_modules/` to the config for `directory-named-webpack-plugin` in the webpack config fixes it.

I've added a pull request over at the `gatsby-starter-universal` repo to make this the default config, since it seems a pretty sane assumption that modules inside node_modules should take care of their own decisions on file naming.

```
plugins: [new DirectoryNamedWebpackPlugin({
        exclude: /node_modules/
      })],
```

Thanks a bunch for your help. Sorry for taking up your time with an issue caused somewhere else :)

**Comment by jeremyckahn** [comment]
Oh great, I'm glad you got to the root of the issue! This all makes sense. Thanks for following up with this, @andru. I'm glad to have helped! 🙂
