### ISSUE TITLE
Default import issue

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jeremyckahn/shifty#114]
Hi,

I'm forwarding an issue mentioned in progressbar.js. The gist is here: https://github.com/kimmobrunfeldt/progressbar.js/issues/256

This import exmaple doesn't seem to work (I quickly tested with node shell):

```js
> const shifty = require('shifty');
undefined
> shifty.tween({ from: { x: 0 }, to: { x: 10 } });
Thrown:
TypeError: shifty.tween is not a function
```

**Comment by jeremyckahn** [comment]
Hi @kimmobrunfeldt! Thanks for logging this issue. I think this is a result of my bundling of Shifty for ES6 environments. I think the most practical solution for CommonJS loaders is to do what @RoyMudie did here: https://github.com/kimmobrunfeldt/progressbar.js/issues/256#issuecomment-598230415

...Which sure enough reveals [an error in my documentation](https://github.com/jeremyckahn/shifty#loading-shifty). 😅Apologies about that. I will fix that for you when I get a chance!

**Comment by jeremyckahn** [comment]
Note: This should be improved in 2.9.1: All modules are now published as ES6 modules. https://github.com/jeremyckahn/shifty/commit/3180c28345a2c10e44aca37a21a18b63c10814ab
