### ISSUE TITLE
error in '2.15.0' from UglifyJs 

### ISSUE THREAD

**Issue by Hilbertangers** [jeremyckahn/shifty#129]
dist/shifty.js   appear es6 arrow function  **()=>**

![image](https://user-images.githubusercontent.com/21299424/103056253-633a9180-45d7-11eb-9678-33014b892812.png)

**Comment by jeremyckahn** [comment]
Yikes! Thank you for reporting this. It’s almost certainly due to the [recent upgrade to Webpack 5](https://github.com/jeremyckahn/shifty/commit/f99630160f81dbfd0e738164c3e0a13fdd65e986). I’ll prioritize a fix for this and follow up when I have something!

**Comment by jeremyckahn** [comment]
This should be fixed in [`v2.15.1`](https://github.com/jeremyckahn/shifty/releases/tag/v2.15.1). Please let me know if you run into any other issues. Thanks again for reporting this @Hilbertangers!
