### ISSUE TITLE
Timeout Handler not using the correct currentTime

### ISSUE THREAD

**Issue by ZainManji** [jeremyckahn/shifty#60]
For the way I want to use Shifty, I want to be able to seek to any point in a Tweenable's duration, but I never really want to seek to the end of the duration since the stop() function will get called in TimeoutHandler and I don't want to stop the tween.

As a result, what I tried to do is check if the millisecond I'm providing the seek function is >= the Tweenable object's duration, and if it is, change the millisecond to a value just smaller than the duration to ensure that stop() never gets called.
However, even after this check, it seemed that stop() would still get called because, the timeoutHandler_isEnded variable in timeoutHandler() would turn true because of the way currentTime was being calculated.

@SBoudrias and I noticed that in seek() when creating the timestamp to pass to timeoutHandler, you call now(), and then when creating the currentTime variable in TimeoutHandler() you call now() again. As a result of calling now() a second time, it isn't the same as the now() call in seek(). As a result there can be a mismatch when calculating currentTime and timeoutHandler_isEnded, which can result in an inaccurate value of the timeoutHandler_offset and can result in stop() being called if you didn't want to.

I made a simple fix in the following link.
https://github.com/ZainManji/shifty/blob/master/src/shifty.core.js

You just need to call now() once and pass a reference to it.

**Comment by jeremyckahn** [comment]
@SBoudrias I just noticed this, but [the test you provided](https://github.com/SBoudrias/shifty/compare/failing-test-%2360) doesn't actually make any assertions.  It's currently throwing an error:

````
Uncaught Error: stop shouldn't be called
````

I should have caught this before.  Is ea344c2 actually fixing your problem?  Should the test be updated?

**Comment by SBoudrias** [comment]
Yeah the fix have been fixing our issue.

**Comment by jeremyckahn** [comment]
Hmm.  I didn't experience this issue myself, so I'm not sure what an effective test might be.  When you have some time, can you try correcting the test to not throw an uncaught error and make an assertion?

**Comment by SBoudrias** [comment]
Oh yeah, I can take care of that. I'll try to tackle this one tomorrow.
