### ISSUE TITLE
Per-property duration value(s)

### ISSUE THREAD

**Issue by adrianvoica** [jeremyckahn/shifty#67]
Here's a new thing that I want to implement: per-property duration values.
Instead of using
{
 ....
   duration : 1000
  ...
}
we should allow "duration" to be an object with each property specifying its own duration, and, even better, a start delay, something like this:
{
  'x' : [10, 2000],
 'y' : [1000, 500],
 'rot' : [500, 3000]
}
and thus, one Tweenable instance takes care of many properties in one go. The maximum duration should be extracted by parsing and choosing the maximum 'start' + 'duration' (in our case the maximum is [500, 3000] = 3500ms).
All the properties that are declared in 'from' but not specified in 'duration' use the maximum amount of time and have no start delay.
Hopefully, this will not introduce a lot of logic, but the results will bring some real simplicity in the code that is using the tweenables.
Cheers!

**Comment by adrianvoica** [comment]
For instance, in the "attachment-demo.html" example, instead of using 20 tweenable object (1 for each of the 20 DIV elements), we could then use 1 single, comprehensible Tweenable instance. Less data, less CPU wasted time, more performance, cleaner and tidier code.

**Comment by jeremyckahn** [comment]
Hi @adrianvoica, thanks for filing this issue.  I feel that the timing/sequencing functionality that you are describing goes beyond the scope of what Shifty is meant for.  I imagine that this would bloat the core logic quite a bit.

There are other projects that are built on top of Shifty to provide similar functionality to what you are describing.  You may want to take a look at [ShiftyTimelineAnimation](https://github.com/ZainManji/ShiftyTimelineAnimation) or [Rekapi](http://rekapi.com).  ShiftyTimelineAnimation may not give you the delay functionality you are looking for, but it is very lightweight.  Rekapi is a broader and somewhat heavier library, but it will handle the sophisticated sequencing you are looking for with pretty good performance.  Would either of those solutions work for you?

**Comment by adrianvoica** [comment]
Yeah, maybe it would add too much logic. 
I think that look-ahead optimization would give it enough juice to work really well in my scenarios, so I'll stick with that, see how it goes.

**Comment by jeremyckahn** [comment]
Sounds like a plan.  If you come up with an implementation for this ticket that doesn't add too much overhead, we can revisit it.
