### ISSUE TITLE
put default easing options into documentation / github page

### ISSUE THREAD

**Issue by flyon** [jeremyckahn/shifty#75]
the homepage sais "A collection of Robert Penner's easing functions have been adapted for use with Shifty and are included in the standard distribution.".

.. that's nice, but I cannot find anywhere what those functions are. I only see easeOutQuart,bounce and swingFromTo in the examples

**Comment by jeremyckahn** [comment]
Fixed and pushed.  Thanks for the suggestion!

**Comment by flyon** [comment]
quick work! :+1: 
tnx for the library, it's working great

**Comment by jeremyckahn** [comment]
Thanks for the feedback!  I'm glad to know it's working for you.
