### ISSUE TITLE
1.4 breaking seek

### ISSUE THREAD

**Issue by SBoudrias** [jeremyckahn/shifty#77]
Looks like the 1.4 release is breaking `seek`. Not sure what changed, and I haven't investigated the issue yet.

**Comment by jeremyckahn** [comment]
Yikes!  Sorry about that.  The unit tests are still passing, so that's a little surprising.  Do you have a test case that reproduces the issue?

**Comment by jeremyckahn** [comment]
If you don't have one, don't worry about it — I should have some time tomorrow to get to the bottom of this.

**Comment by SBoudrias** [comment]
I don't have a reduced test case, but I can point you where the bug is.

It's [these lines](https://github.com/jeremyckahn/shifty/blob/master/dist/shifty.js#L105-L108), since the [code do a check on the timestamp](https://github.com/jeremyckahn/shifty/compare/1.3.11...1.4.1#diff-b3fc9765aebaa666bcc8ab44ea96924cR199), the value of `normalizedPosition` is always 0 when it's triggered from a `seek` call.

**Comment by jeremyckahn** [comment]
Got it.  It must be something to do with the recent "delay" functionality.  I'll bet this can be demonstrated with a unit test that utilizes both the delay functionality as well as `seek`.

**Comment by jeremyckahn** [comment]
I just pushed and released a fix([1.4.2](https://github.com/jeremyckahn/shifty/releases/tag/1.4.2)).  [Careless mistake on my part](https://github.com/jeremyckahn/shifty/commit/b83f272f692472a44f8c21141f89f2245a7a3c23).  Sorry about that.  Thanks for reporting!
