### ISSUE TITLE
root is null when module is run in strict mode

### ISSUE THREAD

**Issue by Lrnk** [jeremyckahn/shifty#81]
The build process I'm using enforces strict mode on each of the projects dependencies. This causes the .call(null) trick for getting 'this' to be global scope to fail (it contains null).
Do you think this is worth remedying? It would certainly help me! Cheers.

**Comment by jeremyckahn** [comment]
Hi @Lrnk, thanks for the reporting this!  Yes, this should definitely be addressed.  I haven't seen this issue myself, so it's hard for me to make and test a fix.  Could you please put together a Pull Request (or at least provide steps to reproduce) if it's not too much trouble?

**Comment by jeremyckahn** [comment]
Fixed by #82.
