### ISSUE TITLE
Possible to use SetInterval or SetTimout instead?

### ISSUE THREAD

**Issue by McFarts** [jeremyckahn/shifty#83]
I'm using this to render hp orbs in my rpg game. But, when using requestanimationFrame and when u alt tab, or lose focus to the game window (in chrome atleast), request animation screws up the tweening process:

For example going from 2 to 15:
![](https://i.gyazo.com/e5a6c3f98d410e07478745320abfb32b.png)

Once I alt tab, or go to a new page, and then come back... The tween stops and then fires back at 15.  

If we use  setInterval or setTimeout instead, this won't happen. Any idea on how I can change it? Love the plugin ~ thx

**Comment by jeremyckahn** [comment]
Hi @McFarts, I'm glad you like Shifty!  You can use `setTimeout` for scheduling with [`setScheduleFunction`](http://jeremyckahn.github.io/shifty/dist/doc/classes/Tweenable.html#method_setScheduleFunction).  However, I strongly recommend using `setTimeout` instead of `setInterval`.  `setInterval` is not recommended to use for animation timing, as "late" intervals stack up excessively and create a performance bottleneck.

**Comment by McFarts** [comment]
@jeremyckahn  I'm having an issue. I set the setScheduleFunction to `setTimeout`, but when you go to a different tab and come back to the window the tween stopped.

**Comment by jeremyckahn** [comment]
Hm, I'm not sure what the issue might be without seeing the code myself.  I know that the function works, as I've used it myself to solve the same problem that you're having: https://github.com/jeremyckahn/genetic/blob/0302017cf821980308674c897d4b01274dbfa358/app/scripts/genetic.tweenable.js#L25

Keep in mind that the argument to `setScheduleFunction` is a function reference — don't invoke it.  Is it possible that the tween just completed by the time you switched the tab back?

**Comment by McFarts** [comment]
Hmm. I'm not sure what Genetic Tween is, is that an extension to Shifty? I'll give it a try.

I just changed the `DEFAULT_SCHEDULE_FUNCTION` to ` setTimeout `in the source file.


This is the code I'm using:

```
	 var tweenable = new Tweenable();
 
						 

						tweenable.tween({
						  from: { chealth: 2 },
						  to:   { chealth: 45 },
						  duration: 1000,
							  step: function(object){
									 
									 console.log(object);
									 
							  },
							  finish: function (object) { 
									console.log(object);
							  }
						});
```

If you run this, and then go to a different tab for 5 seconds after like 100ms after it started and then come back it will show:
![](https://i.gyazo.com/0c0558c4b01533239f79c9b106e6d358.png)

Something like this.  The tween for some reason doesn't render when you're not active on the current page (as you know).

**Comment by jeremyckahn** [comment]
Ahh.  Sorry, I didn't explain the code I linked to before: I built a small helper on top of Shifty to batch `step` operations in the application I was building.  I was just demonstrating a way to use `setScheduleFunction`.

Anyways, I think the issue with the code you provided is that the tween is not set up to loop.  Shifty tweens run once and then just stop — they do not loop.  One way to fix this is to wrap the `tween` call in a function and then just call that function again in your `finish` handler.

FWIW, [Rekapi](http://rekapi.com/), which is built on top of Shifty, supports animation looping.  Shifty is just meant to be a bit more lightweight and minimalist.

**Comment by McFarts** [comment]
Hmm. I see now! I am a very functional thinker so the objects/extending / using lodash, and all that  stuff is something I'm not very versed in :(.  I see how you made setScheduleFunction work now. I would of never known that's how'd you do it though. I was just thinking you'd set it to the setTimout or something, lol.

'Shifty tweens run once and then just stop', but the issue is why does it stop when the browser page is not active? That part just doesn't make sense to me, is it a Chrome / browser issue? You would think the loop would continue to run regardless if a page is active.  Just seems so weird.

I'm going to try wrapping it into a function and calling it, maybe that will work. If not, I'm totally stumped and will try Rekapi if all else falses. I myself, do love the minimalist approach.

**Comment by jeremyckahn** [comment]
> 'Shifty tweens run once and then just stop', but the issue is why does it stop when the browser page is not active? That part just doesn't make sense to me, is it a Chrome / browser issue? You would think the code would continue to run regardless if a page is active. Just seems so weird.

`setTimeout` callbacks will always execute on time(ish), even if running in an inactive tab.  That's a key differentiator between `setTimeout` and `requestAnimationFrame`.  `requestAnimationFrame` callbacks are delayed significantly by the browser when running in an inactive tab.

> why does it stop when the browser page is not active?

The code sample you provided has a `duration` of 1000 milliseconds.  Perhaps the tween is just completing sooner than you are able to switch back to the tab?

**Comment by McFarts** [comment]
We're f'd. (Excuse my language).

Look here:

https://jsfiddle.net/Dillybob/15aa0sm9/1/

Press run, quickly go to a different tab, then come back.  Looks like the browser's have nerfed setInterval as well, which doesn't update on a unFocused tab. What a joke.  I guess there is no way around this.

**Comment by jeremyckahn** [comment]
Maybe try `setTimeout`?  I'm not sure how `setInterval` might handle inactive tabs, I haven't used that function in years.

**Comment by McFarts** [comment]
@jeremyckahn  I did some researching.

I switched and used the script inside Web-Workers instead and just passed the data through web workers `postMessage` method.  Runs fine when alt-tabbed, but it utilizes another thread. But that's okay :)

All is good, thanks for sticking with me ~

**Comment by jeremyckahn** [comment]
That's... a very interesting way to solve the problem.  Nice!

I'm really surprised the `setTimeout`'s accuracy is affected by deactivating the browser tab.  This feels like somewhat new browser behavior.  Thanks for following up.

**Comment by jeremyckahn** [comment]
Going back to this project for a moment: https://github.com/jeremyckahn/genetic (let it run for a minute or so to see some activity)

Granted, it's hard to tell what is going on if you don't know anything about the project, but the point is that the dots continue to update when I switch to another tab.  Genetic is using Shifty and `setTimeout` for the animation.  Therefore, I am somewhat confused as to why you are experiencing different behavior.

FWIW, I am on the latest Chrome Stable channel.

**Comment by McFarts** [comment]
I think it has something to do with the way we (or you) use time.

http://stackoverflow.com/a/5927432/1254837

`Just make your animation function tick by elapsed time in the real world.`  If the loop is running off the real world time, when switching tabs it doesn't affect it. But, when just using normal setTimeout or setInterval it does.  From what I got it anyways, lol.  But, yeah.

**Comment by jeremyckahn** [comment]
Shifty calculates its per-tick state based on actual time elapsed: https://github.com/jeremyckahn/shifty/blob/e6a0cf6d532bbdffd9ab98385d370568945fa6f0/src/shifty.core.js#L184

The issue isn't the accuracy of the computed tween state, the issue is updates not happening as frequently as desired.  It looks like this isn't something that can be accounted for outside of a solution like the one you found with the WebWorkers.  Oh well!

**Comment by McFarts** [comment]
Hmm seems odd. Most likely it's on my end though! Haha.
