### ISSUE TITLE
Remove exclamation marks from comment blocks

### ISSUE THREAD

**Issue by ABM-Dan** [jeremyckahn/shifty#84]
Considering how thislibrary is distributed when minified, it doesn't make much sense for all the jsdoc comment blocks to use /*!, can we please remove them so more minifiers will work properly?

**Comment by jeremyckahn** [comment]
Hi @ABM-Dan, thanks for filing this ticket.  The `/!*` blocks are necessary to prevent [`yuidoc`](https://github.com/jeremyckahn/shifty/blob/01ea2a611f207d7acebdd757ea7346f29c243192/Gruntfile.js#L113-L125) from rendering [private function annotation blocks](https://github.com/jeremyckahn/shifty/blob/01ea2a611f207d7acebdd757ea7346f29c243192/src/shifty.core.js#L43).  I'm not sure how else this might be handled.  Do you have any suggestions?

**Comment by ABM-Dan** [comment]
No clue to be honest, but this is possibly the only js library to behave like this, have you investigated other libraries for similar approaches?

**Comment by ABM-Dan** [comment]
Maybe using @private ?

**Comment by jeremyckahn** [comment]
We can't use `@private`, because then those functions will show up in the "private" section of the generated docs, which is not preferable.  Probably the easiest thing to do is replace the `@` annotations with `#` or something else that YUIDoc doesn't recognize.  Can you use the `dist` files in your build process in the meantime?

**Comment by ABM-Dan** [comment]
YUIDoc says 

> Indicates a member that should not be used externally. Although YUIDoc does not generate documentation for @private blocks, YUIDoc comments are still a nice, structured way to document internals in source code. All methods and properties are assumed to be public unless marked as private or protected.

Did you test it already? Does it indeed create an empty mention?

**Comment by jeremyckahn** [comment]
Oh hey!  That works out nicely.  What I mentioned about rendering the `@private` methods was something I was recalling from memory, so I could be wrong.  If it's as simple as switching to `@private`, then so much the better.  I'll test this out when I have a little time — if it works, I'll convert the annotations.

**Comment by ABM-Dan** [comment]
Let's hope it does :)

**Comment by jeremyckahn** [comment]
@ABM-Dan, please review the referenced PR.  If it looks good to you, I will build it into a new release.

**Comment by ABM-Dan** [comment]
This is pretty much perfect.

**Comment by jeremyckahn** [comment]
Great!  I should have a chance to put together a new release in the next day or two.

**Comment by ABM-Dan** [comment]
It didn't wreck the API tho, right?

**Comment by jeremyckahn** [comment]
No, it seems to be working just fine.  I think I was incorrectly recalling a quirk about the documentation tool that I was using before YUIDoc.  YUIDoc is much better!

**Comment by jeremyckahn** [comment]
Released as [1.5.2](https://github.com/jeremyckahn/shifty/releases/tag/1.5.2) thanks again for reporting!

**Comment by ABM-Dan** [comment]
No, thank you!
